# Generated by Django 6.0.5 on 2026-05-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('exam', 'Пробный экзамен'), ('testing', 'Входное тестирование'), ('meeting', 'Встреча с учителем')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Предмет')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Кафедра/отделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль учителя',
                'verbose_name_plural': 'Профили учителей',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Предмет')),
                ('target_class', models.CharField(blank=True, max_length=10, verbose_name='Класс поступления')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('max_participants', models.PositiveIntegerField(default=1, verbose_name='Максимум мест')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущее количество')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('canceled', 'Отменен')], default='open', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event', verbose_name='Мероприятие')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='events.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('attended', 'Присутствовал'), ('canceled', 'Отменен'), ('no_show', 'Не явился')], default='registered', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата явки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.slot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['slot', 'status'], name='events_regi_slot_id_c2028c_idx'), models.Index(fields=['user', 'status'], name='events_regi_user_id_0e863b_idx'), models.Index(fields=['registered_at'], name='events_regi_registe_a6ca06_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'registered')), fields=('slot', 'user'), name='unique_active_registration_per_slot_user')],
            },
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['event', 'status', 'start_time'], name='events_slot_event_i_40745e_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['teacher', 'start_time'], name='events_slot_teacher_498f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['subject'], name='events_slot_subject_a17952_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['target_class'], name='events_slot_target__1a3ba3_idx'),
        ),
    ]
