# Generated by Django 6.0.5 on 2026-05-07 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('number', models.CharField(max_length=20, verbose_name='Номер кабинета')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['floor', 'number'],
                'constraints': [models.UniqueConstraint(fields=('floor', 'number'), name='unique_classroom_floor_number')],
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='events.classroom', verbose_name='Кабинет'),
        ),
    ]
