# Generated by Django 6.0.5 on 2026-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_classroom_slot_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название класса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='available_classes',
            field=models.ManyToManyField(blank=True, help_text='Если классы не выбраны, слот доступен всем.', related_name='slots', to='events.schoolclass', verbose_name='Доступно классам'),
        ),
    ]
