# Generated by Django 5.2.14 on 2026-05-22 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_schoolclass_slot_available_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_guest_students', models.BooleanField(default=False, verbose_name='Разрешить запись школьников без регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки безопасности',
                'verbose_name_plural': 'Настройки безопасности',
            },
        ),
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_active_registration_per_slot_user',
        ),
        migrations.AddField(
            model_name='registration',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email незарегистрированного школьника'),
        ),
        migrations.AddField(
            model_name='registration',
            name='guest_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО незарегистрированного школьника'),
        ),
        migrations.AddField(
            model_name='registration',
            name='guest_school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_registrations', to='events.schoolclass', verbose_name='Класс незарегистрированного школьника'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['guest_email', 'status'], name='events_regi_guest_e_58eb8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'registered'), ('user__isnull', False)), fields=('slot', 'user'), name='unique_active_registration_per_slot_user'),
        ),
    ]
