# Generated by Django 6.0.5 on 2026-05-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0003_schoolclass_slot_available_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='events.schoolclass', verbose_name='Класс'),
        ),
    ]
